---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: ".chef/encrypted_data_bag_secret"

platforms:
  - name: ubuntu-14.04

suites:
  - name: server_base
    run_list:
      - role[server--base]
    attributes:
      packages:
        - curl
      chruby:
        default: 2.2.2
        rubies:
          2.2.2: true

  - name: dev_base
    run_list:
      - role[dev--base]
    attributes:
      users: david_muto
      authorization:
        sudo:
          users:
            - vagrant
      chruby:
        default: 2.2.3
        rubies:
          2.2.3: true

  - name: apps_dude
    run_list:
      - role[apps--dude]
    attributes:
      authorization:
        sudo:
          users:
            - vagrant
