---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -d vendor
  chef_server_url: "https://chef.sweeper.io/organizations/sweeper"
  encrypted_data_bag_secret_key_path: ".chef/encrypted_data_bag_secret"

platforms:
  - name: ubuntu-14.04

suites:
  - name: base
    run_list:
      - role[base]
    attributes:
