name             "dude"
maintainer       "Sweeper"
maintainer_email "developers@sweeper.io"
license          "mit"
description      "Installs/Configures dude"
long_description "Installs/Configures dude"
version          "0.1.0"
